export { default as CustomerContactDetails } from './CustomerContactDetails';
export { default as CustomerDataManagement } from './CustomerDataManagement';
export { default as CustomerEditForm } from './CustomerEditForm';
export { default as CustomerEmailsSummary } from './CustomerEmailsSummary';
export { default as CustomerOrders } from './CustomerOrders';
export { default as CustomerCases } from './CustomerCases';
export { default as CustomerInvoicesSummary } from './CustomerInvoicesSummary';
export { default as CustomerListTable } from './CustomerListTable';
export { default as CustomerNotes } from './CustomerNotes';
